import { iconMarkup } from './icons/icons.js';
import { evaluateProgressCondition } from '../engine/core/progression/ProgressionEngine.js';

export function renderBoardWorkspace(workspaceEl,{caseData,stateManager,eventBus}){
  let focusId=null; const pendingTargets=new Set();
  workspaceEl.innerHTML=`<section class="jn-board jn-board--free jn-anim-section-enter">
    <header class="jn-board__header"><div><span class="jn-board__eyebrow jn-mono">INVESTIGATION BOARD / FREE WORKSPACE</span><h1>لوحة التحقيق</h1><p>العناصر المكتشفة تبقى في القائمة. أضف إلى اللوحة فقط ما تريد تحليله، ثم حرّكه واربطه بطريقتك.</p></div><div class="jn-board__status" data-role="board-status"></div></header>
    <div class="jn-board__layout">
      <aside class="jn-board-tray"><div class="jn-board-tray__title"><span class="jn-mono">DISCOVERED ITEMS</span><strong>مواد التحقيق</strong></div><div class="jn-board-tray__legend"><span><i class="is-person"></i>شخص</span><span><i class="is-evidence"></i>دليل</span></div><div data-role="tray"></div></aside>
      <main class="jn-board-canvas"><div class="jn-board-paper"><div class="jn-board-paper__head"><div><span class="jn-mono">CASE CONNECTION MAP</span><strong>مساحة المحقق</strong><small>اللوحة تبدأ فارغة. أضف العناصر من القائمة، ثم اختر بطاقة كمركز ربط.</small></div><button class="jn-board-add-note" data-action="add-note">+ ملاحظة</button></div><div class="jn-board-map" data-role="map"><svg class="jn-board-threads" data-role="threads"></svg><div class="jn-board-nodes" data-role="nodes"></div><div class="jn-board-notes" data-role="notes"></div></div><div class="jn-board-compose" data-role="compose"></div></div></main>
    </div></section>`;
  const tray=workspaceEl.querySelector('[data-role=tray]'),nodes=workspaceEl.querySelector('[data-role=nodes]'),notesEl=workspaceEl.querySelector('[data-role=notes]'),compose=workspaceEl.querySelector('[data-role=compose]'),status=workspaceEl.querySelector('[data-role=board-status]'),map=workspaceEl.querySelector('[data-role=map]'),threads=workspaceEl.querySelector('[data-role=threads]');
  const state=()=>stateManager.getState();
  function available(){const st=state(),out=[];(caseData.people||[]).filter(p=>!p.unlockWhen||evaluateProgressCondition(p.unlockWhen,st)).forEach(p=>out.push({id:`person:${p.id}`,kind:'person',ref:p.fileNumber||p.id,title:p.name,sub:role(p),image:p.boardImage||p.photo||p.image||null,initials:p.initials||''}));(caseData.evidence||[]).filter(e=>st.evidenceState?.[e.id]?.discovery==='discovered').forEach(e=>out.push({id:`evidence:${e.id}`,kind:'evidence',ref:e.reference||e.id,title:e.title,sub:'دليل مكتشف',image:e.boardImage||e.image||e.previewImage||null}));return out}
  const placedIds=()=>state().boardPlacedItems||[]; const links=()=>state().boardLinks||[]; const positions=()=>state().boardPositions||{}; const notes=()=>state().boardNotes||[];
  function setPlaced(ids){stateManager.setState(s=>({...s,boardPlacedItems:[...new Set(ids)]}))}
  function addToBoard(id){if(!placedIds().includes(id))setPlaced([...placedIds(),id]);render()}
  function removeFromBoard(id){setPlaced(placedIds().filter(x=>x!==id));stateManager.setState(s=>({...s,boardLinks:(s.boardLinks||[]).filter(l=>l.from!==id&&l.to!==id)}));if(focusId===id)focusId=null;pendingTargets.delete(id);render()}
  function neighbors(id){const r=new Set();links().forEach(l=>{if(l.from===id)r.add(l.to);if(l.to===id)r.add(l.from)});return r}
  function defaultPos(i){return{x:4+(i%3)*31,y:7+Math.floor(i/3)*29}}
  function render(){const all=available(),valid=new Set(all.map(x=>x.id)),placed=placedIds().filter(id=>valid.has(id));if(placed.length!==placedIds().length)setPlaced(placed);const boardItems=placed.map(id=>all.find(x=>x.id===id)).filter(Boolean),boardSet=new Set(placed),focusNeighbors=focusId?neighbors(focusId):new Set();status.innerHTML=`<strong class="jn-mono">${String(boardItems.length).padStart(2,'0')}</strong><span>على اللوحة</span>`;
    tray.innerHTML=all.length?all.map(x=>`<article class="jn-board-tray-card ${boardSet.has(x.id)?'is-on-board':''}">${trayVisual(x)}<div><small>${e(x.sub)}</small><b>${e(x.title)}</b><span class="jn-mono">${e(x.ref)}</span></div>${boardSet.has(x.id)?`<button data-remove="${ea(x.id)}" title="إزالة من اللوحة">−</button>`:`<button data-add="${ea(x.id)}">إضافة</button>`}</article>`).join(''):`<div class="jn-board-empty">لا توجد مواد متاحة بعد.</div>`;
    const pos=positions();nodes.innerHTML=boardItems.map((x,i)=>{const p=pos[x.id]||defaultPos(i);return `<button class="jn-board-node is-${x.kind} ${focusId===x.id?'is-focus':''} ${pendingTargets.has(x.id)?'is-pending':''} ${focusNeighbors.has(x.id)?'is-linked-to-focus':''}" data-node="${ea(x.id)}" style="left:${clamp(p.x,0,82)}%;top:${clamp(p.y,0,78)}%"><span class="jn-board-node__pin"></span>${visual(x)}<span class="jn-board-node__copy"><span class="jn-board-node__type">${x.kind==='person'?'ملف شخص':'دليل'}</span><strong>${e(x.title)}</strong><small class="jn-mono">${e(x.ref)}</small></span></button>`}).join('');
    notesEl.innerHTML=notes().map(n=>`<article class="jn-board-note" data-note="${ea(n.id)}" style="left:${clamp(n.x??8,0,84)}%;top:${clamp(n.y??12,0,80)}%"><span class="jn-board-note__pin"></span><textarea data-note-text="${ea(n.id)}" placeholder="اكتب فرضيتك...">${e(n.text||'')}</textarea><button data-delete-note="${ea(n.id)}">×</button></article>`).join('');renderComposer(boardItems,focusNeighbors);
    tray.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addToBoard(b.dataset.add));tray.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeFromBoard(b.dataset.remove));workspaceEl.querySelector('[data-action=add-note]')?.addEventListener('click',addNote);workspaceEl.querySelector('[data-action=clear-focus]')?.addEventListener('click',clearFocus);workspaceEl.querySelector('[data-action=save-links]')?.addEventListener('click',saveLinks);workspaceEl.querySelectorAll('[data-delete-note]').forEach(b=>b.onclick=()=>deleteNote(b.dataset.deleteNote));workspaceEl.querySelectorAll('[data-note-text]').forEach(t=>t.oninput=()=>updateNote(t.dataset.noteText,t.value));enableDrag(nodes.querySelectorAll('[data-node]'),'node');enableDrag(notesEl.querySelectorAll('[data-note]'),'note');requestAnimationFrame(drawThreads)}
  function renderComposer(items,focusNeighbors){if(!items.length){compose.innerHTML=`<div class="jn-board-selection is-idle"><strong>اللوحة فارغة</strong><p>أضف من القائمة فقط العناصر التي تريد مقارنتها.</p></div>`;return}if(!focusId){compose.innerHTML=`<div class="jn-board-selection is-idle"><strong>اختر بطاقة على اللوحة لبدء الربط</strong><p>لا يوجد سجل روابط منفصل؛ الروابط تظهر مباشرة كخيوط على اللوحة.</p></div>`;return}const f=items.find(x=>x.id===focusId),pending=[...pendingTargets].map(id=>items.find(x=>x.id===id)).filter(Boolean);compose.innerHTML=`<div class="jn-board-selection is-active"><div><span>مركز الربط</span><strong>${e(f?.title||'')}</strong><small>${focusNeighbors.size} روابط حالية</small></div><div><span>روابط جديدة</span><strong>${pending.length}</strong><small>${pending.length?pending.map(x=>e(x.title)).join(' · '):'اختر البطاقات المراد ربطها'}</small></div><div class="jn-board-selection__actions"><button class="jn-btn jn-btn--primary" data-action="save-links" ${pending.length?'':'disabled'}>حفظ الروابط</button><button class="jn-btn jn-btn--ghost" data-action="clear-focus">إنهاء</button></div></div>`}
  function select(id){if(!focusId){focusId=id;pendingTargets.clear();render();return}if(id===focusId){clearFocus();return}const existing=links().find(l=>(l.from===focusId&&l.to===id)||(l.from===id&&l.to===focusId));if(existing){stateManager.setState(s=>({...s,boardLinks:(s.boardLinks||[]).filter(l=>l.id!==existing.id)}));render();return}pendingTargets.has(id)?pendingTargets.delete(id):pendingTargets.add(id);render()}
  function saveLinks(){if(!focusId||!pendingTargets.size)return;const add=[];for(const target of pendingTargets){if(!links().some(l=>(l.from===focusId&&l.to===target)||(l.from===target&&l.to===focusId)))add.push({id:`link-${Date.now()}-${add.length}`,from:focusId,to:target,type:'related',createdAt:Date.now()})}stateManager.setState(s=>({...s,boardLinks:[...(s.boardLinks||[]),...add]}));add.forEach(l=>eventBus?.emit('board:linkCreated',l));pendingTargets.clear();render()}
  function clearFocus(){focusId=null;pendingTargets.clear();render()}
  function addNote(){const n={id:`note-${Date.now()}`,text:'',x:8,y:10};stateManager.setState(s=>({...s,boardNotes:[...(s.boardNotes||[]),n]}));render()}
  function deleteNote(id){stateManager.setState(s=>({...s,boardNotes:(s.boardNotes||[]).filter(n=>n.id!==id)}));render()}
  function updateNote(id,text){stateManager.setState(s=>({...s,boardNotes:(s.boardNotes||[]).map(n=>n.id===id?{...n,text}:n)}))}
  function savePosition(id,x,y,type){if(type==='node')stateManager.setState(s=>({...s,boardPositions:{...(s.boardPositions||{}),[id]:{x,y}}}));else stateManager.setState(s=>({...s,boardNotes:(s.boardNotes||[]).map(n=>n.id===id?{...n,x,y}:n)}))}
  function enableDrag(els,type){els.forEach(el=>{let sx,sy,ox,oy,moved=false;el.onpointerdown=ev=>{if(ev.target.closest('textarea,[data-delete-note]'))return;const mr=map.getBoundingClientRect(),r=el.getBoundingClientRect();sx=ev.clientX;sy=ev.clientY;ox=r.left-mr.left;oy=r.top-mr.top;el.setPointerCapture?.(ev.pointerId);el.onpointermove=mv=>{if(Math.hypot(mv.clientX-sx,mv.clientY-sy)>5)moved=true;if(!moved)return;const x=clamp((ox+mv.clientX-sx)/mr.width*100,0,84),y=clamp((oy+mv.clientY-sy)/mr.height*100,0,82);el.style.left=x+'%';el.style.top=y+'%';drawThreads()};el.onpointerup=up=>{el.onpointermove=null;const mr2=map.getBoundingClientRect(),r2=el.getBoundingClientRect(),x=clamp((r2.left-mr2.left)/mr2.width*100,0,84),y=clamp((r2.top-mr2.top)/mr2.height*100,0,82);savePosition(type==='node'?el.dataset.node:el.dataset.note,x,y,type);if(!moved&&type==='node')select(el.dataset.node)}}})}
  function drawThreads(){const mr=map.getBoundingClientRect();threads.setAttribute('viewBox',`0 0 ${mr.width} ${mr.height}`);threads.innerHTML=links().map(l=>{const a=nodes.querySelector(`[data-node="${CSS.escape(l.from)}"]`),b=nodes.querySelector(`[data-node="${CSS.escape(l.to)}"]`);if(!a||!b)return'';const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect(),x1=ar.left-mr.left+ar.width/2,y1=ar.top-mr.top+18,x2=br.left-mr.left+br.width/2,y2=br.top-mr.top+18;return `<line class="jn-board-thread" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"/>`}).join('')}
  function trayVisual(x){return x.image?`<span class="jn-board-tray-thumb"><img src="${ea(x.image)}" alt=""></span>`:`<span>${iconMarkup(x.kind==='person'?'people':'evidence')}</span>`}
  function visual(x){return x.image?`<span class="jn-board-node__photo"><img src="${ea(x.image)}" alt="" draggable="false"></span>`:`<span class="jn-board-node__photo is-placeholder">${x.kind==='person'?`<b>${e(x.initials||'؟')}</b>`:iconMarkup('evidence')}</span>`}
  render(); window.addEventListener('resize',drawThreads,{passive:true});
}
function role(p){if(p?.role==='victim')return 'الضحية';return p?.identity?.occupation||p?.publicRoleLabel||'ملف شخص'}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))} function e(v=''){const d=document.createElement('div');d.textContent=String(v);return d.innerHTML} function ea(v=''){return e(v).replace(/"/g,'&quot;')}
